jobs:
- job: test
  timeoutInMinutes: 20
  steps:
  - task: NodeTool@0 
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    inputs:
      versionSpec: '16.x'
  - script: npm ci --no-optional
  - script: npm test
